### ISSUE TITLE
Merge Sort in C++

### ISSUE THREAD

**Issue by Gaurav8604** [prabhjotschugh/The-Algorithms-Cpp#22]
Implementation of merge sort in c++ that takes O(nlogn) time complexity in the Arrays section.

**Comment by Gaurav8604** [comment]
Please assign me this issue under the hactoberfest 2023 tag

**Comment by prabhjotschugh** [comment]
Hi Gaurav!
Someone already contributed the code for all the sorting algorithms. You can contribute something else.
